[config]
reload_apps = false   # we reload manually via set-wallpaper.sh

[templates.waybar-colors]
input_path  = "~/.config/matugen/templates/waybar-colors.css.tera"
output_path = "~/.cache/matugen/waybar-colors.css"

[templates.rofi-colors]
input_path  = "~/.config/matugen/templates/rofi-colors.rasi.tera"
output_path = "~/.cache/matugen/rofi-colors.rasi"

[templates.kitty-colors]
input_path  = "~/.config/matugen/templates/kitty-colors.conf.tera"
output_path = "~/.cache/matugen/kitty-colors.conf"

[templates.foot-colors]
input_path  = "~/.config/matugen/templates/foot-colors.ini.tera"
output_path = "~/.cache/matugen/foot-colors.ini"

[templates.mako-colors]
input_path  = "~/.config/matugen/templates/mako-colors.ini.tera"
output_path = "~/.cache/matugen/mako-colors.ini"

[templates.hyprland-colors]
input_path  = "~/.config/matugen/templates/hyprland-colors.conf.tera"
output_path = "~/.cache/matugen/hyprland-colors.conf"

[templates.hyprlock-colors]
input_path  = "~/.config/matugen/templates/hyprlock-colors.conf.tera"
output_path = "~/.cache/matugen/hyprlock-colors.conf"

[templates.walker-colors]
input_path  = "~/.config/matugen/templates/walker-colors.css.tera"
output_path = "/tmp/walker-colors.css"
