font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# matugen generates this file; kitty picks it up on next launch or Ctrl+Shift+F5
include ~/.cache/matugen/kitty-colors.conf

cursor_shape           beam
cursor_blink_interval  0

scrollback_lines 10000

enable_audio_bell no

window_padding_width 8

tab_bar_style powerline

shell_integration enabled
